[icons]
icons = "awesome4"

[theme]
theme = "nord-dark"


[[block]]
block = "music"
player = "spotify"

[[block]]
block = "disk_space"
alert = 10.0
info_type = "available"
interval = 20
path = "/"

[[block]]
block = "memory"

[[block]]
block = "cpu"
format = "$icon $barchart $utilization"
interval = 1

[[block]]
block = "bluetooth"
mac = "AC:1D:06:4C:19:FA"

[[block]]
block = "bluetooth"
mac = "2C:41:A1:CB:1A:84"

[[block]]
block = "net"
device = "wlp1s0"
format = "$ssid $ip ^icon_net_down $speed_up.eng(prefix:K) ^icon_net_up $speed_down.eng(prefix:K)"
missing_format = "Disconnected"

[[block]]
block = "vpn"
driver = "mullvad"
format_connected = " $flag"
format_disconnected = " $icon"

[[block]]
block = "custom"
command = ''' tailscale status --json | jq '.Self | if .Online then { state: "Good", text: "tailscale up" } else { state: "Idle", text: "tailscale down" } end ' '''
json = true

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "$icon $percentage "
interval = 10

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 5
